spring.application.name=FarmView

# H2データベースの接続設定
spring.datasource.url=jdbc:h2:file:./data/farmview
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Consoleを有効にする
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPAの設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true